### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by sguillia** [kufii/CodeSnap#47] opened 2020-09-08 13:22 UTC
Code is selected but Codesnap shows empty window

![Capture du 2020-09-08 15-20-58](https://user-images.githubusercontent.com/15984272/92481637-ec73b700-f1e6-11ea-8b8d-7dfb3ca0bdf9.png)

Version: 1.49.0-insider
Commit: 8c9b4015feb0297d99c8051c35e85d208ffe83e3
Date: 2020-09-03T07:13:55.843Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-112-generic

**Comment by NatoBoram** [comment] 2020-09-08 15:08
Duplicate of #46

**Closed** 2020-09-11 17:54 UTC
