### ISSUE TITLE
"CodeSnap" doesn't work on Windows

### ISSUE THREAD

**Issue by Delta-in-hub** [kufii/CodeSnap#48] opened 2020-09-12 13:14 UTC
版本: 1.49.0 (user setup)
提交: e790b931385d72cf5669fcefc51cdf65990efa5d
日期: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by kufii** [comment] 2020-09-12 20:27
duplicate of https://github.com/kufii/CodeSnap/issues/46

**Closed by kufii** 2020-09-12 20:27 UTC
